'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute(ConfigurationName:="IFileTransferService")>  _
Public Interface IFileTransferService
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFileTransferService/UploadFile", ReplyAction:="http://tempuri.org/IFileTransferService/UploadFileResponse")>  _
    Sub UploadFile(ByVal bytes() As Byte)
    
    <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IFileTransferService/UploadFile", ReplyAction:="http://tempuri.org/IFileTransferService/UploadFileResponse")>  _
    Function BeginUploadFile(ByVal bytes() As Byte, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
    
    Sub EndUploadFile(ByVal result As System.IAsyncResult)
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Public Interface IFileTransferServiceChannel
    Inherits IFileTransferService, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Partial Public Class FileTransferServiceClient
    Inherits System.ServiceModel.ClientBase(Of IFileTransferService)
    Implements IFileTransferService
    
    Private onBeginUploadFileDelegate As BeginOperationDelegate
    
    Private onEndUploadFileDelegate As EndOperationDelegate
    
    Private onUploadFileCompletedDelegate As System.Threading.SendOrPostCallback
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    Public Event UploadFileCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
    
    Public Sub UploadFile(ByVal bytes() As Byte) Implements IFileTransferService.UploadFile
        MyBase.Channel.UploadFile(bytes)
    End Sub
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Function BeginUploadFile(ByVal bytes() As Byte, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements IFileTransferService.BeginUploadFile
        Return MyBase.Channel.BeginUploadFile(bytes, callback, asyncState)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Sub EndUploadFile(ByVal result As System.IAsyncResult) Implements IFileTransferService.EndUploadFile
        MyBase.Channel.EndUploadFile(result)
    End Sub
    
    Private Function OnBeginUploadFile(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Dim bytes() As Byte = CType(inValues(0),Byte())
        Return Me.BeginUploadFile(bytes, callback, asyncState)
    End Function
    
    Private Function OnEndUploadFile(ByVal result As System.IAsyncResult) As Object()
        Me.EndUploadFile(result)
        Return Nothing
    End Function
    
    Private Sub OnUploadFileCompleted(ByVal state As Object)
        If (Not (Me.UploadFileCompletedEvent) Is Nothing) Then
            Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
            RaiseEvent UploadFileCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
        End If
    End Sub
    
    Public Overloads Sub UploadFileAsync(ByVal bytes() As Byte)
        Me.UploadFileAsync(bytes, Nothing)
    End Sub
    
    Public Overloads Sub UploadFileAsync(ByVal bytes() As Byte, ByVal userState As Object)
        If (Me.onBeginUploadFileDelegate Is Nothing) Then
            Me.onBeginUploadFileDelegate = AddressOf Me.OnBeginUploadFile
        End If
        If (Me.onEndUploadFileDelegate Is Nothing) Then
            Me.onEndUploadFileDelegate = AddressOf Me.OnEndUploadFile
        End If
        If (Me.onUploadFileCompletedDelegate Is Nothing) Then
            Me.onUploadFileCompletedDelegate = AddressOf Me.OnUploadFileCompleted
        End If
        MyBase.InvokeAsync(Me.onBeginUploadFileDelegate, New Object() {bytes}, Me.onEndUploadFileDelegate, Me.onUploadFileCompletedDelegate, userState)
    End Sub
End Class
